package Behavioral.Command;

public class Customer {
    private static int lastGenratedId=0; //autogenerated
    private int code;
    private String name;
    private int totalSalePrice;
    private int totalReceipt;

    public int getCode() {
        return code;
    }

    public String getName() {
        return name;
    }

    Customer(String name) {
        this.name = name;
        lastGenratedId++;
        this.code = lastGenratedId;
        this.totalReceipt=0;
        this.totalSalePrice=0;
    }

    public void getBalance() {
        int diff = totalSalePrice-totalReceipt;
        if(diff>0) {
            System.out.println(diff+" dr");
        }else {
            System.out.println(-1*diff+" cr");
        }
    }

    public void addSalePrice(int i) {
        this.totalSalePrice+=i;
    }

    public void addReceipt(int i) {
        this.totalReceipt+=i;
    }
}
